// Ingredientes básicos de despensa que casi todo el mundo tiene en casa.
// No se incluyen en la lista de la compra.
export const INGREDIENTES_BASICOS = [
  "sal",
  "pimienta",
  "aceite",
  "aceite de oliva",
  "aceite vegetal",
  "agua",
  "azúcar",
  "azucar",
  "vinagre",
  "ajo en polvo",
  "cebolla en polvo",
  "pimentón",
  "pimenton",
  "orégano",
  "oregano",
  "papel film",
  "papel de horno",
  "bicarbonato",
  "levadura",
  "colorante",
  "laurel",
  "tomillo",
  "romero",
  "curry en polvo",
  "comino en polvo",
  "canela en polvo",
  "nuez moscada",
];
